// design-sync prepare step (cfg.buildCmd). The site has no publishable package,
// so this assembles a virtual one under .design-sync/.cache/pkg/:
//   1. index.ts   - re-exports every component (from components/ and components/ui/)
//   2. types/     - tsc-generated .d.ts tree (real prop contracts for the design agent)
//   3. compiled.css - Tailwind v4 output of styles.src.css (globals.css + fonts)
// Run from the repo root: node .design-sync/prepare.mjs
import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';

const PKG = '.design-sync/.cache/pkg';
mkdirSync(PKG, { recursive: true });

// 1. entry -------------------------------------------------------------
const SKIP = new Set(['ComponentExample', 'FooterExample', 'TextHoverEffectDemo', 'Example', 'ExampleWrapper']);
const files = [
  ...readdirSync('components').filter((f) => f.endsWith('.tsx')).map((f) => `components/${f}`),
  ...readdirSync('components/ui').filter((f) => f.endsWith('.tsx')).map((f) => `components/ui/${f}`),
];
const lines = ['// generated by .design-sync/prepare.mjs - re-exports every component for the bundle'];
for (const f of files) {
  const s = readFileSync(f, 'utf8');
  const names = new Set();
  for (const m of s.matchAll(/^export\s+(?:default\s+)?(?:function|const|class)\s+([A-Z][A-Za-z0-9]*)/gm)) names.add(m[1]);
  for (const m of s.matchAll(/^export\s*\{([^}]+)\}/gm))
    for (const n of m[1].split(',')) { const t = n.trim().split(/\s+as\s+/).pop().trim(); if (/^[A-Z][A-Za-z0-9]*$/.test(t)) names.add(t); }
  if (![...names].some((n) => !SKIP.has(n))) continue;
  const mod = `../../../${f.replace(/\.tsx$/, '')}`; // relative, not '@/': tsc keeps specifiers verbatim and ts-morph has no alias map
  const dm = s.match(/^export default (?:function\s+)?([A-Z][A-Za-z0-9]*)/m);
  if (dm && !SKIP.has(dm[1])) lines.push(`export { default as ${dm[1]} } from '${mod}';`);
  lines.push(`export * from '${mod}';`);
}
writeFileSync(`${PKG}/index.ts`, lines.join('\n') + '\n');

if (!existsSync(`${PKG}/package.json`)) writeFileSync(`${PKG}/package.json`, JSON.stringify({
  name: 'thu-tides-website', version: '0.1.0', private: true,
  description: "design-sync virtual package: the site's components re-exported with tsc-generated type declarations",
  types: 'types/index.d.ts',
}, null, 2) + '\n');
if (!existsSync(`${PKG}/tsconfig.json`)) writeFileSync(`${PKG}/tsconfig.json`, JSON.stringify({
  extends: '../../tsconfig.json',
  compilerOptions: { baseUrl: '../../..', rootDir: '../../..', outDir: './types', declaration: true, emitDeclarationOnly: true, noEmit: false, noCheck: true, skipLibCheck: true, incremental: false, paths: { '@/*': ['./*'] } },
  include: ['./index.ts', '../../../components/**/*.tsx', '../../../lib/*.ts', '../../../data/*.ts', '../../../types/*.ts'],
  exclude: ['../../../node_modules', '../../../tests'],
}, null, 2) + '\n');

// 2. declarations ------------------------------------------------------
rmSync(`${PKG}/types`, { recursive: true, force: true });
execSync(`node_modules/.bin/tsc -p ${PKG}/tsconfig.json`, { stdio: 'inherit' });
writeFileSync(`${PKG}/types/index.d.ts`, '// design-sync: types root entry so the ts-morph parse sees the whole tree\nexport * from "./.design-sync/.cache/pkg/index";\n');

// 3. stylesheet --------------------------------------------------------
execSync(`node .ds-sync/node_modules/.bin/tailwindcss -i .design-sync/styles.src.css -o ${PKG}/compiled.css`, { stdio: 'inherit' });
console.error(`prepare: ${files.length} component files -> ${PKG}/index.ts, types/, compiled.css`);
